language: go
go:
  - 1.2

before_script:
  - go get gopkg.in/check.v1

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - goveralls -repotoken He1pfPjOZQhkFq6mDHfkj1xDXVn7hMHoB
